// SPDX-License-Identifier: MIT
pragma solidity ^0.8.9;
// linter warnings (red underline) about pragma version can igonored!

// contract code will go here
contract Inbox {
    string public message;
    //* automatically a getter is generated by the solidity compiler

    // memory is like temporaty storage
    constructor(string memory initialMessage){
        message = initialMessage;
    }

    function setMessage(string memory newMessage) public{
        message = newMessage;
    }
}
